version: 2
updates:
  - package-ecosystem: github-actions
    directory: .github/workflows
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - thatleda

  - package-ecosystem: npm
    directory: /
    rebase-strategy: auto
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    assignees:
      - thatleda
    allow:
      - dependency-type: direct
    versioning-strategy: auto
    pull-request-branch-name:
      separator: /
    groups:
      playwright:
        patterns:
          - '@playwright*'
          - playwright
      lint:
        patterns:
          - '@antfu/eslint-config'
          - eslint*
          - emoji-regex
      testing:
        patterns:
          - '@testing-library*'
          - happy-dom
          - vitest
          - '@vue/test-utils'
