catalog:
  '@antfu/eslint-config': 6.7.3
  '@asbjorn/eslint-plugin-groq': 2.0.0
  '@nuxt/fonts': 0.12.1
  '@nuxt/image': 2.0.0
  '@nuxtjs/color-mode': 4.0.0
  '@playwright/test': 1.57.0
  '@portabletext/types': 4.0.1
  '@portabletext/vue': 1.0.14
  '@sanity/client': 7.14.0
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/vue': 8.1.0
  '@vitejs/plugin-vue': 6.0.3
  '@vue/test-utils': 2.4.6
  '@vueuse/core': 14.1.0
  '@vueuse/nuxt': 14.1.0
  dayjs: 1.11.19
  dotenv-cli: 11.0.0
  emoji-regex: 10.6.0
  eslint: 9.39.2
  eslint-plugin-playwright: 2.4.0
  eslint-plugin-testing-library: 7.15.4
  groq: 5.1.0
  happy-dom: 20.0.11
  lighthouse: 13.0.1
  netlify-cli: 23.13.0
  nuxt: 4.2.2
  nuxt-graphql-middleware: 5.3.2
  playwright: 1.57.0
  typescript: 5.9.3
  vitest: 4.0.16
  vue: 3.5.26
  vue-router: 4.6.4

catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@netlify/edge-bundler@14.9.0'
  - '@netlify/zip-it-and-ship-it@14.1.14'
  - '@netlify/serverless-functions-api@2.7.2'
  - chokidar@4.0.3
  - pino@9.14.0
  - undici-types@6.21.0
  - '@graphql-tools/*'
  - semver@6.3.1
  - ua-parser-js@1.0.41

packages:
  - .
