packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true

catalog:
  '@antfu/eslint-config': 8.2.0
  '@nuxt/fonts': 0.14.0
  '@nuxt/image': 2.0.0
  '@nuxtjs/color-mode': 4.0.0
  '@playwright/test': 1.59.1
  '@portabletext/types': 4.0.2
  '@portabletext/vue': 1.0.14
  '@sanity/client': 7.22.0
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/vue': 8.1.0
  '@vitejs/plugin-vue': 6.0.6
  '@vue/test-utils': 2.4.6
  '@vueuse/core': 14.2.1
  '@vueuse/nuxt': 14.2.1
  dayjs: 1.11.20
  dotenv-cli: 11.0.0
  emoji-regex: 10.6.0
  eslint: 10.2.1
  eslint-plugin-playwright: 2.10.2
  eslint-plugin-testing-library: 7.16.2
  eslint-plugin-vuejs-accessibility: 2.5.0
  groq: 5.22.0
  happy-dom: 20.9.0
  lighthouse: 13.1.0
  netlify-cli: 26.0.0
  nuxt: 4.4.4
  nuxt-graphql-middleware: 5.4.0
  playwright: 1.59.1
  typescript: 6.0.3
  vitest: 4.1.5
  vue: 3.5.33
  vue-router: 5.0.6

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver
