catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

catalog:
  '@antfu/eslint-config': 6.5.1
  '@asbjorn/eslint-plugin-groq': 2.0.0
  '@nuxt/fonts': 0.12.1
  '@nuxt/image': 2.0.0
  '@nuxtjs/color-mode': 4.0.0
  '@playwright/test': 1.57.0
  '@portabletext/types': 3.0.0
  '@portabletext/vue': 1.0.14
  '@sanity/client': 7.13.1
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/vue': 8.1.0
  '@vitejs/plugin-vue': 6.0.2
  '@vue/test-utils': 2.4.6
  '@vueuse/core': 14.1.0
  '@vueuse/nuxt': 14.1.0
  date-fns: 4.1.0
  dotenv-cli: 11.0.0
  emoji-regex: 10.6.0
  eslint: 9.39.1
  groq: 4.20.3
  happy-dom: 20.0.11
  lighthouse: 13.0.1
  netlify-cli: 23.12.3
  nuxt: 4.2.1
  nuxt-graphql-middleware: 5.2.3
  playwright: 1.57.0
  typescript: 5.9.3
  vitest: 4.0.15
  vue: 3.5.25
  vue-router: 4.6.3
