import { expect, test } from '@playwright/test'

test('displays navigation with home link', async ({ page }) => {
  await page.goto('/')

  await expect(page.getByLabel('Main navigation')).toBeVisible()
  await expect(page.getByLabel('Main navigation').getByRole('link', { name: 'Howling wolf icon' })).toBeVisible()
  await expect(page.getByLabel('Main navigation').getByRole('link', { name: 'Home' })).not.toBeVisible()
  await expect(page.getByLabel('Main navigation').getByRole('button', { name: 'Language English' })).toBeVisible()
  await expect(page.getByLabel('Main navigation').getByRole('button', { name: 'Toggle color mode' })).toBeVisible()
  await expect(page.getByLabel('Main navigation').getByRole('link', { name: 'Who?' })).toBeVisible()
  await expect(page.getByLabel('Main navigation').getByRole('link', { name: 'Blog' })).toBeVisible()
  await expect(page.getByLabel('Main navigation').getByRole('link', { name: 'Working with Leda' })).toBeVisible()
  await expect(page.getByLabel('Main navigation').getByRole('link', { name: 'Contact' })).toBeVisible()
  await expect(page.getByLabel('Main navigation').getByRole('link', { name: 'Resume' })).toBeVisible()
})

test('displays the CV in English', async ({ page }) => {
  await page.goto('/resume')

  await expect(page.getByRole('link', { name: 'Print / Save as PDF' })).toBeVisible()
  await expect(page.getByText('SENIOR FULLSTACK SOFTWARE ENGINEER')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Profile' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Skills' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Experience' })).toBeVisible()
  await expect(page.getByText('DIU MarTech Solutions')).toBeVisible()
  await expect(page.getByText('Verlag C.H.Beck')).toBeVisible()
  await expect(page.getByText('Career break')).toBeVisible()
  await expect(page.getByText('grover.com')).toBeVisible()
  await expect(page.getByText('Tallence AG')).toBeVisible()
  await expect(page.getByText('sum.cumo Sapiens GmbH')).toBeVisible()
  await expect(page.getByText('moebel.de')).toBeVisible()
  await expect(page.getByText('EOS Technology Solutions')).toBeVisible()
  await expect(page.getByText('CarGarantie')).toBeVisible()
  await expect(page.getByText('DrehPunkt GmbH')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Education' })).toBeVisible()
  await expect(page.getByText('University of Rostock')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Languages' })).toBeVisible()
  await expect(page.getByText('German, English, Russian')).toBeVisible()
  await expect(page.getByText('Spanish, French')).toBeVisible()
  await expect(page.getByText('Ukrainian, Portuguese, Mandarin, Japanese')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Additional' })).toBeVisible()
  await expect(page.getByText('Certified Scrum Master')).toBeVisible()
})
