name: Vulfden CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NUXT_SANITY_PROJECT_ID: brvct6ie
      NUXT_SANITY_DATASET: production
      URL: https://leda.fyi
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - name: Run install
        run: yarn install --frozen-lockfile
      - name: Build production bundle
        run: yarn build
      - name: Lint files
        run: yarn lint:ci
      - name: Run tests
        run: yarn test
